ALTER TABLE pacientes
  ADD COLUMN IF NOT EXISTS foto         VARCHAR(300),
  ADD COLUMN IF NOT EXISTS colonia      VARCHAR(100),
  ADD COLUMN IF NOT EXISTS ciudad       VARCHAR(100),
  ADD COLUMN IF NOT EXISTS codigo_postal VARCHAR(10);
